# Shared RDS Postgres instance — one DB server, multiple logical DBs (one per env).
# Cost-optimised: db.t4g.micro, single-AZ, 20 GB gp3, no backups, no PI, no enhanced monitoring.

data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

resource "aws_db_subnet_group" "shared" {
  name       = "infusethink-shared"
  subnet_ids = data.aws_subnets.default.ids

  tags = {
    Name = "infusethink-shared"
  }
}

# Publicly accessible so terraform (and devs) can manage logical DBs/roles from laptops.
# Password-protected; rotate via `terraform apply -replace=module.shared.random_password.db_master`.
resource "aws_security_group" "database" {
  name        = "infusethink-shared-db"
  description = "Shared Postgres - allow 5432 from anywhere (password-protected)"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "Postgres - allowlisted CIDRs"
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = var.db_allowed_cidrs
  }

  egress {
    description      = "Allow all outbound"
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  tags = {
    Name = "infusethink-shared-db"
  }
}

resource "aws_db_instance" "shared" {
  identifier     = "infusethink-shared"
  engine         = "postgres"
  engine_version = "18.3"
  instance_class = "db.t4g.micro"

  allocated_storage = 20
  storage_type      = "gp3"

  db_subnet_group_name   = aws_db_subnet_group.shared.name
  vpc_security_group_ids = [aws_security_group.database.id]
  publicly_accessible    = true

  username                    = "infusethink"
  manage_master_user_password = true

  # Cost-cutting: no bells and whistles
  backup_retention_period      = 0
  multi_az                     = false
  monitoring_interval          = 0
  performance_insights_enabled = false
  storage_encrypted            = false
  deletion_protection          = false
  skip_final_snapshot          = true
  apply_immediately            = true

  tags = {
    Name = "infusethink-shared"
  }
}

# Master password is auto-generated by RDS and stored in Secrets Manager.
# Look it up so we can expose it as a (sensitive) module output for the
# postgresql provider to consume.
data "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_db_instance.shared.master_user_secret[0].secret_arn
}
