---
# Pre-commit hooks for code quality and consistency
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Configure default behavior
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  # Pre-commit's own hooks for basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
        args: [--multi]
      - id: check-toml
        name: Check TOML syntax
      - id: check-json
        name: Check JSON syntax
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-added-large-files
        name: Check for large files
        args: [--maxkb=1000]
      - id: debug-statements
        name: Check for debug statements

  # Ruff for Python linting and formatting (replaces Black, isort, flake8, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      # Run the linter
      - id: ruff
        name: Ruff linter
        args: [--fix]
        types: [python]
      # Run the formatter
      - id: ruff-format
        name: Ruff formatter
        types: [python]

  # Pyright for type checking
  - repo: local
    hooks:
      - id: pyright
        name: Pyright type checker
        entry: pyright
        language: system
        types: [python]
        pass_filenames: false

  # Commitizen for commit message validation
  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.7.0
    hooks:
      - id: conventional-gitmoji

  # Additional Python-specific checks
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.8
    hooks:
      - id: uv-lock
        name: Check uv lock file is up to date

# Configure CI mode for faster execution
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
