[project]
name = "infusethink-iac"
version = "0.1.0"
requires-python = ">=3.13"

[dependency-groups]
dev = [
  "commitizen>=4.9.1",
  "cz-conventional-gitmoji>=0.7.0",
  "dprint-py>=0.50.0",
  "pre-commit>=4.2.0",
]

[tool.commitizen]
name = "cz_gitmoji"
version_provider = "commitizen"
version_scheme = "semver"
tag_format = "v$version"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
bump_message = "bump: version $current_version → $new_version"
